Activity page
CS-565-SP-2023/cs565 pull request #2
Opened 2023-05-01 18:36 UTC by alanzyt311

2023-05-03 05:10 UTC, chbkull requested changes

2023-05-03 05:10 UTC, chbkull commented on src/App.tsx
>                <NavBar />
- [x] Remove Navbar for the time being, may be distracting for study

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +        <div className="welcome-message">Welcome to the Music Sheet Identification activity!</div>
- [x] Improved blurb about study, informed consent, gift card opportunity

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +          <label htmlFor="email">Your Email</label>
- [ ] Denote that email is an optional field, for gift card raffle only

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +          <label htmlFor="experience">Your Music Experience</label>
- [ ] Experience as radio button multiple choice rather than freeform text

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +        {errorMessage && <div className="error-message">{errorMessage}</div>}
- [ ] More graceful error handling for experience not provided

2023-05-03 05:10 UTC, chbkull commented on public/manifest.json
> +    "short_name": "React App",
- [ ] More appropriate page title
- [ ] More appropriate favicon

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/01_activity_screen.tsx
> +              Thank you for your participation, Now you can continue or click
- [ ] Leads to some wonky spacing when this message shows up

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/01_activity_screen.tsx
> +          pitch: pitchIdx.get(note.y),
- [ ] goldSymbols assumes that the bottom most line is pitch "1", so change to 1-indexed instead of 0-indexed

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/01_activity_screen.tsx
- [ ] On my device, there is some scrolling needed to see the symbol buttons. Try and set stuff up such that no scrolling is needed

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/01_activity_screen.tsx
> +    <React.Fragment>
- [ ] Some sort of instructions on how to carry out the task

2023-05-03 05:10 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/02_thankyou_screen.tsx
> +                            <h1>Thank you for your participation!</h1>
- [ ] Longer / more formal note here

2023-05-03 16:53 UTC, alanzyt311 commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +          <label htmlFor="experience">Your Music Experience</label>
What would be the choices? Should it be a scale of 1-5 familiarity? Or the texts such as Many, Few, None?

2023-05-04 03:52 UTC, chbkull approved these changes

2023-05-04 03:52 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/01_activity_screen.tsx
> +              <Draggable
- [x] The way these draggables are set up, they can span the entire music-staff div, which means that they can actually block some of the buttons. Would it be possible to reorganize the div structure such that it can only be dragged over the staff itself, and the buttons aren't blocked?

2023-05-04 03:52 UTC, chbkull commented on src/FrontEnd/Pages/ParticipantSide/00_entrance_screen.tsx
> +          <label htmlFor="experience">Your Music Experience</label>
I would do it with text:
- No experience
- Some prior experience
- Actively work with it
- Prefer not to answer

2023-05-04 04:02 UTC, merged